management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: health, metrics, prometheus
    base-path: "/actuator"
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
baseUrl: ${AUTH0_INT_CLIENT_AUD:https://api.dev.entur.io}/shared-mobility-to-ref/v1
