common:
  env: dev
  ingress:
    host:
      shared-mobility-to-ref.dev.entur.io
  configmap:
    enabled: true
    data:
      ENVIRONMENT_URL: .dev
      ENVIRONMENT_URL_IO: .dev
      jwt_environment: dev
