common:
  app: shared-mobility-to-ref
  shortname: shmotoref
  team: delingsmobilitet
  ingress:
    enabled: true
    trafficType: public
  service:
    internalPort: 8080
  deployment:
    prometheus:
      enabled: true
      path: "/actuator/prometheus"
    replicas: 2
  container:
    image: <+artifacts.primary.image>
    cpu: 0.3
    memory: 256
    probes:
      liveness:
        path: "/actuator/health/livenessState"
      readiness:
        path: "/actuator/health/readinessState"
  secrets:
    auth:
      - MNG_AUTH0_INT_CLIENT_ID
      - MNG_AUTH0_INT_CLIENT_SECRET
  configmap:
    enabled: true
    data:
      LOG_LEVEL: warn
      TZ: "Europe/Oslo"
auth:
  audience: null
  domain: null
