package no.entur.shared.mobility.to.ref.tomp200.dto

import java.util.Locale
import java.util.Objects
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo
import no.entur.shared.mobility.to.ref.tomp200.dto.TravelSpecification
import no.entur.shared.mobility.to.ref.tomp200.dto.TripPattern
import jakarta.validation.constraints.DecimalMax
import jakarta.validation.constraints.DecimalMin
import jakarta.validation.constraints.Email
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Pattern
import jakarta.validation.constraints.Size
import jakarta.validation.Valid
import io.swagger.v3.oas.annotations.media.Schema

/**
 * 
 * @param type 
 * @param from this string references to information that can be found in the `data sources`. Enlist all prefixes (=rel) from the /collections/datasources/items that apply to a place/location. Default it matches already with 'GPS' (no entry required in the datasources). In case of a custom place (like home address), you can use the 'P:' prefix and add the address to the **places** list of the request/offer/package.
 * @param via use an ID contained in the **places** field, or from an external source, when using coordinates, please use the prefix 'gps:'
 * @param to this string references to information that can be found in the `data sources`. Enlist all prefixes (=rel) from the /collections/datasources/items that apply to a place/location. Default it matches already with 'GPS' (no entry required in the datasources). In case of a custom place (like home address), you can use the 'P:' prefix and add the address to the **places** list of the request/offer/package.
 * @param startTime https://www.rfc-editor.org/rfc/rfc3339#section-5.6, date-time (2019-10-12T07:20:50.52Z)
 * @param endTime https://www.rfc-editor.org/rfc/rfc3339#section-5.6, date-time (2019-10-12T07:20:50.52Z)
 * @param serviceJourneys 
 * @param travelDate https://www.rfc-editor.org/rfc/rfc3339#section-5.6, full-date (2019-10-12)
 */
@JsonIgnoreProperties(
  value = ["type"], // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes(
      JsonSubTypes.Type(value = TravelSpecification::class, name = "travel_specification"),
      JsonSubTypes.Type(value = TripPattern::class, name = "trip_pattern")
)

interface SearchOfferRequestSpecification {
                @get:Schema(example = "null", description = "")
        val type: kotlin.String? 

                @get:Schema(example = "null", description = "this string references to information that can be found in the `data sources`. Enlist all prefixes (=rel) from the /collections/datasources/items that apply to a place/location. Default it matches already with 'GPS' (no entry required in the datasources). In case of a custom place (like home address), you can use the 'P:' prefix and add the address to the **places** list of the request/offer/package.")
        val from: kotlin.String? 

                @get:Schema(example = "null", description = "use an ID contained in the **places** field, or from an external source, when using coordinates, please use the prefix 'gps:'")
        val via: kotlin.collections.List<kotlin.String>? 

                @get:Schema(example = "null", description = "this string references to information that can be found in the `data sources`. Enlist all prefixes (=rel) from the /collections/datasources/items that apply to a place/location. Default it matches already with 'GPS' (no entry required in the datasources). In case of a custom place (like home address), you can use the 'P:' prefix and add the address to the **places** list of the request/offer/package.")
        val to: kotlin.String? 

                @get:Schema(example = "null", description = "https://www.rfc-editor.org/rfc/rfc3339#section-5.6, date-time (2019-10-12T07:20:50.52Z)")
        val startTime: java.time.OffsetDateTime? 

                @get:Schema(example = "null", description = "https://www.rfc-editor.org/rfc/rfc3339#section-5.6, date-time (2019-10-12T07:20:50.52Z)")
        val endTime: java.time.OffsetDateTime? 

                @get:Schema(example = "null", description = "")
        val serviceJourneys: kotlin.collections.List<kotlin.String>? 

                @get:Schema(example = "null", description = "https://www.rfc-editor.org/rfc/rfc3339#section-5.6, full-date (2019-10-12)")
        val travelDate: kotlin.String? 


}

