package no.entur.shared.mobility.to.ref.tomp200.dto

import java.util.Locale
import java.util.Objects
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo
import com.fasterxml.jackson.annotation.JsonValue
import no.entur.shared.mobility.to.ref.tomp200.dto.BinaryTicket
import no.entur.shared.mobility.to.ref.tomp200.dto.EKey
import no.entur.shared.mobility.to.ref.tomp200.dto.EKeyEkey
import no.entur.shared.mobility.to.ref.tomp200.dto.EKeyLock
import no.entur.shared.mobility.to.ref.tomp200.dto.ExternalDigitalTicket
import no.entur.shared.mobility.to.ref.tomp200.dto.TypeOfTravelDocument
import jakarta.validation.constraints.DecimalMax
import jakarta.validation.constraints.DecimalMin
import jakarta.validation.constraints.Email
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Pattern
import jakarta.validation.constraints.Size
import jakarta.validation.Valid
import io.swagger.v3.oas.annotations.media.Schema

/**
 * 
 * @param type 
 * @param validity 
 * @param travelDocumentType 
 * @param contentType the media type (IANA)
 * @param base64 long string, memos etc (length 0-10.000)
 * @param ekey 
 * @param lock 
 * @param id 
 * @param &#x60;package&#x60; default string, full names etc (length 0-200)
 * @param leg default string, full names etc (length 0-200)
 * @param asset default string, full names etc (length 0-200)
 * @param traveller default string, full names etc (length 0-200)
 * @param customFields dictionary for extra fields (bilatural agreements)
 */
@JsonIgnoreProperties(
  value = ["travelDocumentType"], // ignore manually set travelDocumentType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the travelDocumentType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "travelDocumentType", visible = true)
@JsonSubTypes(
      JsonSubTypes.Type(value = BinaryTicket::class, name = "AZTECCODE"),
      JsonSubTypes.Type(value = BinaryTicket::class, name = "BARCODE"),
      JsonSubTypes.Type(value = EKey::class, name = "EKEY"),
      JsonSubTypes.Type(value = ExternalDigitalTicket::class, name = "LINK"),
      JsonSubTypes.Type(value = BinaryTicket::class, name = "QRCODE")
)

interface TravelDocument {
                @get:Schema(example = "null", requiredMode = Schema.RequiredMode.REQUIRED, description = "")
        val type: kotlin.String

                @get:Schema(example = "null", requiredMode = Schema.RequiredMode.REQUIRED, description = "")
        val validity: kotlin.collections.List<java.time.OffsetDateTime>

                @get:Schema(example = "null", requiredMode = Schema.RequiredMode.REQUIRED, description = "")
        val travelDocumentType: TypeOfTravelDocument

                @get:Schema(example = "null", requiredMode = Schema.RequiredMode.REQUIRED, description = "the media type (IANA)")
        val contentType: kotlin.String

                @get:Schema(example = "null", requiredMode = Schema.RequiredMode.REQUIRED, description = "long string, memos etc (length 0-10.000)")
        val base64: kotlin.String

                @get:Schema(example = "null", requiredMode = Schema.RequiredMode.REQUIRED, description = "")
        val ekey: EKeyEkey

                @get:Schema(example = "null", requiredMode = Schema.RequiredMode.REQUIRED, description = "")
        val lock: EKeyLock

                @get:Schema(example = "null", description = "")
        val id: kotlin.String? 

                @get:Schema(example = "null", description = "default string, full names etc (length 0-200)")
        val `package`: kotlin.String? 

                @get:Schema(example = "null", description = "default string, full names etc (length 0-200)")
        val leg: kotlin.String? 

                @get:Schema(example = "null", description = "default string, full names etc (length 0-200)")
        val asset: kotlin.String? 

                @get:Schema(example = "null", description = "default string, full names etc (length 0-200)")
        val traveller: kotlin.String? 

                @get:Schema(example = "null", description = "dictionary for extra fields (bilatural agreements)")
        val customFields: kotlin.collections.Map<kotlin.String, kotlin.Any>? 


}

