package no.entur.shared.mobility.to.ref.dto

import io.swagger.v3.oas.annotations.media.Schema

/**
 * An error that the service may send, e.g. in case of invalid input, missing authorization or internal service error.
 * See https://github.com/TOMP-WG/TOMP-API/wiki/Error-handling-in-TOMP for further explanation of error code.
 * @param errorcode The TOMP specific error code. See https://github.com/TOMP-WG/TOMP-API/wiki/Error-handling-in-TOMP
 * for more details of this error.
 * @param type The category of this type of error.
 * @param title A short, human-readable summary of the problem type.  It SHOULD NOT change from occurrence to occurrence of the problem,
 * except to match Content-Language
 * @param status The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
 * @param detail A human-readable explanation specific to this occurrence of the problem, could match Content-Language
 * @param instance A URI reference that identifies the specific occurrence of the problem.
 * It may or may not yield further information if dereferenced.
 */
data class Error(
    @Schema(
        example = "null",
        description = """The TOMP specific error code. See https://github.com/TOMP-WG/TOMP-API/wiki/Error-handling-in-TOMP for more 
            |details of this error.""",
    )
    val errorcode: Int? = null,
    @Schema(example = "null", description = "The category of this type of error.")
    val type: String? = null,
    @Schema(
        example = "null",
        description = """A short, human-readable summary of the problem type.  It SHOULD NOT change from occurrence to occurrence of the 
            |problem, except to match Content-Language""",
    )
    val title: String? = null,
    @Schema(
        example = "null",
        description = "The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.",
    )
    val status: Int? = null,
    @Schema(
        example = "null",
        description = "A human-readable explanation specific to this occurrence of the problem, could match Content-Language",
    )
    val detail: String? = null,
    @Schema(
        example = "null",
        description = """A URI reference that identifies the specific occurrence of the problem.  It may or may not yield further 
            |information if dereferenced.""",
    )
    val instance: String? = null,
)
