package no.entur.shared.mobility.to.ref.dto

/**
 *
 * Values: pOSTPONEDCOMMIT,dEPOSIT,pAYWHENFINISHED,rEQUIREBOOKINGDATA,rETURNAREA,uPFRONTPAYMENT
 */
enum class Scenario {
    POSTPONED_COMMIT,
    DEPOSIT,
    PAY_WHEN_FINISHED,
    REQUIRE_BOOKING_DATA,
    RETURN_AREA,
    UPFRONT_PAYMENT,
}
