apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-to-ref-config
  labels:
    chart: "{{ .Chart.Name }}-to-ref-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  APP_ENV: {{ .Values.environment }}
  APP_VERSION: {{ .Chart.AppVersion }}
  AUTH_DOMAIN: {{ .Values.auth.domain }}
  AUTH_AUDIENCE: {{ .Values.auth.audience }}

