name: "Manual Build and Publish to staging"

on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    name: "Call Build and Deploy to staging"
    uses: ./.github/workflows/build-and-deploy.yml
    secrets: inherit
    with:
      environment: tst
