name: "Manual Run SonarCloud"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        type: string

jobs:
  build:
    name: "Call Build with SonarScan"
    uses: ./.github/workflows/build-with-sonar.yml
    with:
      inputbranch: ${{ inputs.branch }}
    secrets: inherit
