name: "Merge to main"
on:
  push:
    branches:
      - main


jobs:
  build:
    name: "Gradle build and test"
    uses: ./.github/workflows/build.yml
    secrets: inherit

  publish:
    name: "Docker Push and Publish Documentation"
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets: inherit

