name: "Pull Request"

on:
  pull_request:

jobs:
  build:
    name: "Gradle build and test"
    uses: ./.github/workflows/build.yml
    secrets: inherit

  scan:
    name: "CodeQL Scan"
    needs: build
    uses: ./.github/workflows/scan.yml
    secrets: inherit

